dist: trusty
language: go
os: linux

go:
  - 1.10.x

services:
  - mysql

install:
  # ensure that vendor/ is in sync with code and Gopkg.*
  - curl https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -L -o ~/dep && chmod +x ~/dep
  - rm -fr vendor/
  - ~/dep ensure -v
  - git diff --exit-code

script:
  - make init
  - make test-travis
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: Oa4GIV4rgAr+Sa4It/GIGPWO6fVC/pcaRPiaIMfZf+xVXS07EA25CgLw2VvNVwUd7xrAxRfEDQ3fvOHE1ruiGYWjPDvVlZsLIzuOCCifcH3hcpVV6NPBMO4arbfc8NsrOtcOHaoZoOfC8CJFt4buQ+ytjY56gstJMLy7iwbjVh0=
