dist: xenial
language: go

services:
  - mysql

go:
  - 1.12.x
  # - TODO master

matrix:
  allow_failures:
    - go: master

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

env:
  fast_finish: true

install:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check

before_script:
  # ensure that files are not changed
  - make init
  - make format
  - git status
  - git diff --exit-code

script:
  - make test-cover
  - make test-crosscover
  - make test-race

  - make check

after_success:
  - curl https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f cover.out -F cover -X fix
  - ./codecov -f crosscover.out -F crosscover -X fix

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: AysgwfvVB+5AAwhTn0+m3yGywVeEWsBwu2KOGDBBB16T+5ktXxiWK16qMkRHazzruQcYAiM6IXtDz3xT9PMeROr1VmsmnAGPgxE1KOilVioFBqTUAKqxtx0KY5W/RBYgbUueBy2ugC7y3vwuzMq9VkmvQWiGp9Bl5Nm55kExLRc=
